### PR TITLE
Initial attempt at FAKE build for Gluon

### PR DESCRIPTION
**Pull request by panesofglass**
To do:
- [x] build
- [x] versioned builds
- [x] source linking
- [x] run tests
- [x] publish tests to AppVeyor
- [x] package
- [x] generate docs
- [x] publish docs
- [x] tagged builds
- [x] Travis CI ([panesofglass fork](https://travis-ci.org/panesofglass/gluon))
  - [ ] Set up on Tachyus fork /cc @ctaggart

### CODE REVIEW

**Comment by panesofglass** [comment]
@ctaggart, I could use some help when you have a moment. I'm not sure why the version is not getting updated properly.

**Comment by panesofglass** [comment]
@t0yv0, I think this is in a good enough state for a review and possible merge. Thoughts? /cc @ctaggart

**Comment by t0yv0** [comment]
Sorry, why are we bringing the massive build.fsx boilerplate? Versioning and doc generation is already being done in tools, if you are moving this to FAKE let's at least de-duplicate?

**Comment by t0yv0** [comment]
Basically I'm OK with merging if we remove all dead and duplicated build code. Thanks!

**Comment by t0yv0** [comment]
It just dawned on me that this buys us ability to build on OSX and Linux. Sorry for my crabbiness before! Let's do it, kill the powershell. Thanks @panesofglass

**Comment by panesofglass** [comment]
Yep, I did all that just to get the Travis CI build. :) I did not yet remove all the `tools/*.ps1` b/c we may want / need to keep some. One example is `tools/tag.ps1`.

**Comment by t0yv0** [comment]
I'll recode it to Pyhton ;)

**Comment by panesofglass** [comment]
Accept for setting up Travis CI from the Tachyus GitHub account, I think this is ready to roll.

**Comment by t0yv0** [comment]
Good work, thanks!

**Pull request merged**
